# Generated by Django 3.2 on 2022-10-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realstate', '0004_alter_realstate_main_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realstate',
            name='main_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
