# Generated by Django 3.2 on 2022-10-13 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realstate', '0006_alter_realstate_realstate_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realstate',
            name='main_img',
            field=models.ImageField(default='had.jpeg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='realstate',
            name='realstate_title',
            field=models.CharField(max_length=50),
        ),
    ]
