# Generated by Django 3.2 on 2022-10-13 19:51

from django.db import migrations, models
import realstate.models


class Migration(migrations.Migration):

    dependencies = [
        ('realstate', '0007_auto_20221013_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realstateimage',
            old_name='company',
            new_name='realstate',
        ),
        migrations.AlterField(
            model_name='realstate',
            name='main_img',
            field=models.ImageField(default='had.jpeg', upload_to=realstate.models.path_file_name),
        ),
    ]
