# Generated by Django 3.2 on 2022-10-13 19:59

from django.db import migrations, models
import realstate.models


class Migration(migrations.Migration):

    dependencies = [
        ('realstate', '0008_auto_20221013_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realstateimage',
            name='image',
            field=models.ImageField(upload_to=realstate.models.img_file_name),
        ),
    ]
