# Generated by Django 3.2 on 2022-10-14 20:56

from django.db import migrations, models
import realstate.utils


class Migration(migrations.Migration):

    dependencies = [
        ('realstate', '0009_alter_realstateimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realstate',
            name='main_img',
            field=models.ImageField(default='image2.jpeg', upload_to=realstate.utils.path_file_name),
        ),
    ]
