# Generated by Django 3.2 on 2022-10-16 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realstate', '0012_alter_realstate_main_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realstateimage',
            old_name='realstate',
            new_name='realstat',
        ),
    ]
